apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: airflow-web
  template:
    metadata:
      labels:
        app: airflow-web
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.web.port }}
          env:
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                configMapKeyRef:
                  name: airflow-config
                  key: AIRFLOW__CORE__FERNET_KEY
            - name: AIRFLOW__CORE__EXECUTOR
              valueFrom:
                configMapKeyRef:
                  name: airflow-config
                  key: AIRFLOW__CORE__EXECUTOR
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: AIRFLOW__CELERY__RESULT_BACKEND
