apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
stringData:
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: {{ .Values.secrets.database_connection | quote }}
  AIRFLOW__CELERY__RESULT_BACKEND: {{ .Values.secrets.celery_backend | quote }}
